import type { FieldDef, FieldType, Option, RegisterDef } from "@/lib/registers/types";

// Every register in the Hub. Field names match the database columns in
// supabase/migrations; select options match their check constraints.

function opts(labels: Record<string, string>): Option[] {
  return Object.entries(labels).map(([value, label]) => ({ value, label }));
}

function f(type: FieldType, name: string, label: string, extra: Partial<FieldDef> = {}): FieldDef {
  return { type, name, label, ...extra };
}
const text = (n: string, l: string, e?: Partial<FieldDef>) => f("text", n, l, e);
const area = (n: string, l: string, e?: Partial<FieldDef>) => f("textarea", n, l, e);
const date = (n: string, l: string, e?: Partial<FieldDef>) => f("date", n, l, e);
const when = (n: string, l: string, e?: Partial<FieldDef>) => f("datetime", n, l, e);
const num = (n: string, l: string, e?: Partial<FieldDef>) => f("number", n, l, e);
const money = (n: string, l: string, e?: Partial<FieldDef>) => f("money", n, l, e);
const yes = (n: string, l: string, e?: Partial<FieldDef>) => f("boolean", n, l, e);
const email = (n: string, l: string, e?: Partial<FieldDef>) => f("email", n, l, e);
const tel = (n: string, l: string, e?: Partial<FieldDef>) => f("tel", n, l, e);
const pick = (n: string, l: string, options: Option[], e?: Partial<FieldDef>) =>
  f("select", n, l, { options, defaultValue: options[0]?.value, ...e });
const person = (n: string, l: string, e?: Partial<FieldDef>) => f("member", n, l, e);
const ref = (n: string, l: string, register: string, e?: Partial<FieldDef>) => f("ref", n, l, { ref: register, ...e });

export const TRAINING_CATEGORIES = opts({
  induction: "Induction",
  health_safety: "Health and safety",
  safeguarding: "Safeguarding",
  data_protection: "Data protection",
  first_aid: "First aid",
  coshh: "COSHH",
  manual_handling: "Manual handling",
  role_specific: "Role specific",
  other: "Other",
});

export const ABSENCE_KINDS = opts({
  holiday: "Holiday",
  sickness: "Sickness",
  compassionate: "Compassionate",
  unpaid: "Unpaid",
  parental: "Parental",
  other: "Other",
});

export const DOCUMENT_CATEGORIES = opts({
  contract: "Contract",
  id_right_to_work: "ID / right to work",
  dbs: "DBS",
  certificate: "Certificate",
  insurance: "Insurance",
  safety_data_sheet: "Safety data sheet",
  policy: "Policy",
  other: "Other",
});

export const TEMPLATE_KINDS = opts({
  contract: "Contract",
  job_description: "Job description",
  offer_letter: "Offer letter",
  letter: "Letter",
  other: "Other",
});

const staffHub: RegisterDef[] = [
  {
    key: "onboarding",
    module: "staff_hub",
    table: "hub_onboarding_tasks",
    title: "Onboarding",
    singular: "onboarding task",
    description: "Checklist of everything a new starter needs before and during their first weeks.",
    fields: [person("member_id", "Person", { required: true }), text("task", "Task", { required: true }), date("due_on", "Due"),
      yes("done", "Done"), date("done_on", "Done on"), area("notes", "Notes")],
    list: ["member_id", "task", "due_on", "done"],
    titleField: "task",
    order: { column: "due_on", ascending: true },
    due: [{ field: "due_on", label: "Onboarding task due" }],
    closedWhen: { field: "done", values: [true] },
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "training",
    module: "staff_hub",
    table: "hub_training",
    title: "Training",
    singular: "training record",
    description: "Courses completed, with certificate expiry dates.",
    fields: [person("member_id", "Person", { required: true }), text("course", "Course", { required: true }),
      pick("category", "Category", TRAINING_CATEGORIES, { defaultValue: "other" }), text("provider", "Provider"),
      date("completed_on", "Completed"), date("expires_on", "Expires"), area("notes", "Notes")],
    list: ["member_id", "course", "completed_on", "expires_on"],
    titleField: "course",
    order: { column: "expires_on", ascending: true },
    due: [{ field: "expires_on", label: "Training expires" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "competencies",
    module: "staff_hub",
    table: "hub_competencies",
    title: "Competency",
    singular: "competency sign-off",
    description: "Skills a manager has assessed someone as competent in.",
    fields: [person("member_id", "Person", { required: true }), text("competency", "Competency", { required: true }),
      date("assessed_on", "Assessed on"), text("assessed_by", "Assessed by"),
      pick("outcome", "Outcome", opts({ not_yet: "Not yet competent", competent: "Competent", refresher_needed: "Refresher needed" })),
      date("review_on", "Review on"), area("notes", "Notes")],
    list: ["member_id", "competency", "outcome", "review_on"],
    titleField: "competency",
    order: { column: "review_on", ascending: true },
    due: [{ field: "review_on", label: "Competency review" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "supervisions",
    module: "staff_hub",
    table: "hub_supervisions",
    title: "Supervision & spot checks",
    singular: "supervision",
    description: "Supervisions, spot checks of staff and one-to-ones. Staff acknowledge their own.",
    fields: [person("member_id", "Person", { required: true }), date("held_on", "Held on", { required: true }),
      pick("kind", "Type", opts({ supervision: "Supervision", spot_check: "Spot check", one_to_one: "One-to-one", probation_review: "Probation review" })),
      text("carried_out_by", "Carried out by"), area("discussion", "Discussion"), area("actions", "Actions"),
      date("next_due_on", "Next due"), when("acknowledged_at", "Acknowledged by them", { readonly: true })],
    list: ["member_id", "kind", "held_on", "next_due_on", "acknowledged_at"],
    titleField: "held_on",
    order: { column: "held_on", ascending: false },
    due: [{ field: "next_due_on", label: "Supervision due" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "absences",
    module: "staff_hub",
    table: "hub_absences",
    title: "Absence & holiday",
    singular: "absence",
    description: "Holiday, sickness and other leave. Staff request holiday and report sickness themselves.",
    fields: [person("member_id", "Person", { required: true }), pick("kind", "Type", ABSENCE_KINDS),
      date("start_on", "From", { required: true }), date("end_on", "To", { required: true }),
      num("days", "Working days", { min: 0, max: 366, help: "Leave blank to count weekdays between the dates." }),
      area("reason", "Reason"),
      pick("status", "Status", opts({ recorded: "Recorded", requested: "Requested", approved: "Approved", declined: "Declined" })),
      yes("return_to_work_done", "Return-to-work interview done"), area("return_to_work_notes", "Return-to-work notes")],
    list: ["member_id", "kind", "start_on", "end_on", "days", "status"],
    titleField: "kind",
    order: { column: "start_on", ascending: false },
    memberField: "member_id",
    staff: {
      read: true,
      create: {
        label: "Request holiday or report sickness",
        fields: ["kind", "start_on", "end_on", "days", "reason"],
        options: { kind: opts({ holiday: "Holiday", sickness: "Sickness" }) },
      },
    },
  },
  {
    key: "reviews",
    module: "staff_hub",
    table: "hub_reviews",
    title: "Performance",
    singular: "review",
    description: "Probation reviews, appraisals, one-to-ones and improvement plans.",
    fields: [person("member_id", "Person", { required: true }), date("review_on", "Date", { required: true }),
      pick("kind", "Type", opts({ appraisal: "Appraisal", probation: "Probation", one_to_one: "One-to-one", improvement_plan: "Improvement plan" })),
      text("reviewer", "Reviewer"),
      pick("rating", "Rating", opts({ "": "Not rated", exceeds: "Exceeds", meets: "Meets", partly_meets: "Partly meets", below: "Below" })),
      area("strengths", "Strengths"), area("improvements", "Areas to improve"), area("objectives", "Objectives"),
      date("next_review_on", "Next review"), pick("status", "Status", opts({ planned: "Planned", completed: "Completed" }))],
    list: ["member_id", "kind", "review_on", "status", "next_review_on"],
    titleField: "kind",
    order: { column: "review_on", ascending: false },
    due: [{ field: "review_on", label: "Review planned" }, { field: "next_review_on", label: "Next review" }],
    closedWhen: { field: "status", values: ["completed"] },
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "employee-relations",
    module: "staff_hub",
    table: "hub_er_cases",
    title: "Employee relations",
    singular: "case",
    description: "Concerns, grievances, disciplinaries and conflicts. Confidential: staff can raise one but never read the file.",
    fields: [person("member_id", "Person", { required: true }),
      pick("kind", "Type", opts({ concern: "Concern", grievance: "Grievance", disciplinary: "Disciplinary", conflict: "Conflict", capability: "Capability" })),
      date("opened_on", "Opened"), area("summary", "Summary", { required: true }),
      pick("status", "Status", opts({ open: "Open", investigating: "Investigating", hearing: "Hearing", closed: "Closed" })),
      area("investigation", "Investigation"), area("outcome", "Outcome"), date("closed_on", "Closed on")],
    list: ["member_id", "kind", "opened_on", "status"],
    titleField: "kind",
    order: { column: "opened_on", ascending: false },
    closedWhen: { field: "status", values: ["closed"] },
    memberField: "member_id",
    staff: {
      read: false,
      create: {
        label: "Raise a concern or grievance",
        fields: ["kind", "summary"],
        options: { kind: opts({ concern: "Concern", grievance: "Grievance" }) },
      },
    },
  },
  {
    key: "benefits",
    module: "staff_hub",
    table: "hub_benefits",
    title: "Benefits",
    singular: "benefit",
    description: "Benefits each person receives.",
    fields: [person("member_id", "Person", { required: true }), text("benefit", "Benefit", { required: true }), text("value", "Value"),
      date("start_on", "From"), date("end_on", "Until"), area("notes", "Notes")],
    list: ["member_id", "benefit", "value", "end_on"],
    titleField: "benefit",
    order: { column: "created_at", ascending: false },
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "vacancies",
    module: "staff_hub",
    table: "hub_vacancies",
    title: "Vacancies",
    singular: "vacancy",
    description: "Jobs you're recruiting for. Open vacancies appear on your public jobs page.",
    fields: [text("title", "Job title", { required: true }), text("location", "Location"), text("hours", "Hours"), text("pay", "Pay"),
      area("description", "Description"), date("closing_on", "Closing date"),
      pick("status", "Status", opts({ draft: "Draft", open: "Open", closed: "Closed" }))],
    list: ["title", "status", "closing_on"],
    titleField: "title",
    order: { column: "created_at", ascending: false },
    due: [{ field: "closing_on", label: "Vacancy closes" }],
    closedWhen: { field: "status", values: ["closed", "draft"] },
  },
  {
    key: "applicants",
    module: "staff_hub",
    table: "hub_applicants",
    title: "Applicants",
    singular: "applicant",
    description: "People who have applied, and where they are in the process.",
    fields: [ref("vacancy_id", "Vacancy", "vacancies"), text("full_name", "Name", { required: true }), email("email", "Email"),
      tel("phone", "Phone"), area("cover_note", "Their note"),
      pick("stage", "Stage", opts({ applied: "Applied", shortlisted: "Shortlisted", interview: "Interview", offered: "Offered", hired: "Hired", rejected: "Rejected", withdrawn: "Withdrawn" })),
      when("interview_at", "Interview"), yes("right_to_work_checked", "Right to work checked"),
      yes("references_checked", "References checked"), area("notes", "Notes")],
    list: ["full_name", "vacancy_id", "stage", "interview_at"],
    titleField: "full_name",
    order: { column: "created_at", ascending: false },
    closedWhen: { field: "stage", values: ["hired", "rejected", "withdrawn"] },
  },
  {
    key: "templates",
    module: "staff_hub",
    table: "hub_templates",
    title: "Contract templates",
    singular: "template",
    description: "Contracts, job descriptions and letters with {{placeholders}} filled in when issued to someone.",
    fields: [pick("kind", "Type", TEMPLATE_KINDS), text("title", "Title", { required: true }),
      area("body", "Wording", { required: true, help: "Placeholders: {{full_name}}, {{first_name}}, {{email}}, {{job_title}}, {{employment_type}}, {{start_date}}, {{business_name}}, {{today}}" })],
    list: ["title", "kind"],
    titleField: "title",
    order: { column: "title", ascending: true },
  },
  {
    key: "issued-documents",
    module: "staff_hub",
    table: "hub_issued_documents",
    title: "Issued documents",
    singular: "issued document",
    description: "Contracts and letters issued to staff from a template, and whether they've signed.",
    fields: [person("member_id", "Person", { required: true }), pick("kind", "Type", TEMPLATE_KINDS), text("title", "Title", { required: true }),
      area("body", "Wording", { required: true }), yes("requires_signature", "Needs their signature", { defaultValue: "true" }),
      text("signed_name", "Signed as", { readonly: true }), when("signed_at", "Signed", { readonly: true })],
    list: ["member_id", "title", "signed_at"],
    titleField: "title",
    order: { column: "issued_at", ascending: false },
    memberField: "member_id",
    staff: { read: true },
    noCreate: true,
  },
];

const compliance: RegisterDef[] = [
  {
    key: "risks",
    module: "compliance",
    table: "hub_risks",
    title: "Risk register",
    singular: "risk",
    description: "Each risk scored likelihood × severity for the risk matrix.",
    fields: [text("hazard", "Hazard or risk", { required: true }),
      pick("category", "Category", opts({ health_safety: "Health and safety", operational: "Operational", financial: "Financial", legal: "Legal", data: "Data", reputational: "Reputational", other: "Other" })),
      text("who_at_risk", "Who is at risk"),
      pick("likelihood", "Likelihood", opts({ "1": "1 Rare", "2": "2 Unlikely", "3": "3 Possible", "4": "4 Likely", "5": "5 Almost certain" }), { defaultValue: "3" }),
      pick("severity", "Severity", opts({ "1": "1 Negligible", "2": "2 Minor", "3": "3 Moderate", "4": "4 Major", "5": "5 Severe" }), { defaultValue: "3" }),
      num("score", "Score", { readonly: true }), area("existing_controls", "Existing controls"), area("further_actions", "Further actions"),
      text("owner", "Owner"), date("review_on", "Review on"),
      pick("status", "Status", opts({ open: "Open", controlled: "Controlled", closed: "Closed" }))],
    list: ["hazard", "score", "status", "review_on"],
    titleField: "hazard",
    order: { column: "score", ascending: false },
    due: [{ field: "review_on", label: "Risk review" }],
    closedWhen: { field: "status", values: ["closed"] },
  },
  {
    key: "risk-assessments",
    module: "compliance",
    table: "hub_risk_assessments",
    title: "Risk assessments",
    singular: "risk assessment",
    description: "Written assessments for activities and locations.",
    fields: [text("title", "Title", { required: true }), text("activity", "Activity"), text("location", "Location"),
      text("assessed_by", "Assessed by"), date("assessed_on", "Assessed on"),
      area("hazards_and_controls", "Hazards and controls"), date("review_on", "Review on"),
      pick("status", "Status", opts({ current: "Current", draft: "Draft", archived: "Archived" }))],
    list: ["title", "assessed_on", "review_on", "status"],
    titleField: "title",
    order: { column: "review_on", ascending: true },
    due: [{ field: "review_on", label: "Risk assessment review" }],
    closedWhen: { field: "status", values: ["archived"] },
  },
  {
    key: "coshh",
    module: "compliance",
    table: "hub_coshh",
    title: "COSHH register",
    singular: "COSHH assessment",
    description: "Hazardous substances, their safety data sheets and controls.",
    fields: [text("product", "Product", { required: true }), text("supplier", "Supplier"), area("hazards", "Hazards"),
      text("used_for", "Used for"), text("location", "Stored at"), yes("sds_on_file", "Safety data sheet on file"),
      text("ppe", "PPE"), area("controls", "Controls"), area("first_aid", "First aid"),
      date("assessed_on", "Assessed on"), date("review_on", "Review on")],
    list: ["product", "sds_on_file", "review_on"],
    titleField: "product",
    order: { column: "product", ascending: true },
    due: [{ field: "review_on", label: "COSHH review" }],
  },
  {
    key: "incidents",
    module: "compliance",
    table: "hub_incidents",
    title: "Accidents & incidents",
    singular: "incident",
    description: "Accidents, incidents and near misses, and their investigation. Any staff member can report one.",
    fields: [person("member_id", "Reported by"), when("occurred_at", "When", { required: true }), text("location", "Where"),
      pick("kind", "Type", opts({ incident: "Incident", accident: "Accident", near_miss: "Near miss", dangerous_occurrence: "Dangerous occurrence" })),
      text("people_involved", "People involved"), area("description", "What happened", { required: true }),
      text("injury", "Injury"), text("first_aid_given", "First aid given"),
      yes("riddor_reportable", "RIDDOR reportable"), date("reported_to_hse_on", "Reported to HSE on"),
      pick("status", "Status", opts({ open: "Open", investigating: "Investigating", closed: "Closed" })),
      area("investigation", "Investigation findings"), area("root_cause", "Root cause"), area("actions", "Actions"),
      date("closed_on", "Closed on")],
    list: ["occurred_at", "kind", "location", "status"],
    titleField: "kind",
    order: { column: "occurred_at", ascending: false },
    closedWhen: { field: "status", values: ["closed"] },
    memberField: "member_id",
    staff: { read: true, create: { label: "Report an accident or incident", fields: ["occurred_at", "location", "kind", "people_involved", "description", "injury", "first_aid_given"] } },
  },
  {
    key: "safeguarding",
    module: "compliance",
    table: "hub_safeguarding",
    title: "Safeguarding",
    singular: "safeguarding concern",
    description: "Safeguarding concerns and referrals. Staff can raise a concern but can't read the log.",
    fields: [person("member_id", "Raised by"), date("raised_on", "Raised on"), text("person_initials", "Person at risk (initials)"),
      pick("concern_type", "Type", opts({ other: "Other", physical: "Physical", emotional: "Emotional", sexual: "Sexual", neglect: "Neglect", financial: "Financial", discriminatory: "Discriminatory", organisational: "Organisational", self_neglect: "Self-neglect", domestic: "Domestic abuse", modern_slavery: "Modern slavery" })),
      area("description", "Concern", { required: true }), area("action_taken", "Action taken"), text("referred_to", "Referred to"),
      date("referred_on", "Referred on"), pick("status", "Status", opts({ open: "Open", referred: "Referred", closed: "Closed" }))],
    list: ["raised_on", "concern_type", "person_initials", "status"],
    titleField: "concern_type",
    order: { column: "raised_on", ascending: false },
    closedWhen: { field: "status", values: ["closed"] },
    memberField: "member_id",
    staff: { read: false, create: { label: "Raise a safeguarding concern", fields: ["person_initials", "concern_type", "description"] } },
  },
  {
    key: "audits",
    module: "compliance",
    table: "hub_audits",
    title: "Audits & review calendar",
    singular: "audit",
    description: "Checks and reviews on a repeating schedule. Mark one done and the next date is set for you.",
    fields: [text("title", "What", { required: true }), text("area", "Area"),
      pick("frequency", "How often", opts({ monthly: "Monthly", quarterly: "Quarterly", six_monthly: "Every 6 months", annual: "Annually" }), { defaultValue: "annual" }),
      text("owner", "Owner"), date("last_done_on", "Last done"), date("next_due_on", "Next due"), area("notes", "Notes")],
    list: ["title", "frequency", "last_done_on", "next_due_on"],
    titleField: "title",
    order: { column: "next_due_on", ascending: true },
    due: [{ field: "next_due_on", label: "Audit due" }],
  },
  {
    key: "spot-checks",
    module: "compliance",
    table: "hub_spot_checks",
    title: "Quality spot checks",
    singular: "spot check",
    description: "Checks of work quality on site.",
    fields: [date("checked_on", "Date", { required: true }), text("location", "Location or client"), person("member_id", "Staff member checked"),
      text("checked_by", "Checked by"), pick("outcome", "Outcome", opts({ pass: "Pass", advisory: "Advisory", fail: "Fail" })),
      area("findings", "Findings"), area("actions", "Actions"), date("follow_up_on", "Follow up on")],
    list: ["checked_on", "location", "member_id", "outcome"],
    titleField: "location",
    order: { column: "checked_on", ascending: false },
    due: [{ field: "follow_up_on", label: "Spot check follow-up" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "insurance",
    module: "compliance",
    table: "hub_insurance",
    title: "Insurance",
    singular: "insurance policy",
    description: "Insurance policies and renewal dates.",
    fields: [pick("kind", "Type", opts({ public_liability: "Public liability", employers_liability: "Employers' liability", professional_indemnity: "Professional indemnity", vehicle: "Vehicle", property: "Property", contents: "Contents", cyber: "Cyber", other: "Other" })),
      text("insurer", "Insurer"), text("policy_number", "Policy number"), text("cover", "Cover"), money("premium", "Premium"),
      date("start_on", "Start"), date("renewal_on", "Renewal"), text("broker", "Broker"), area("notes", "Notes")],
    list: ["kind", "insurer", "renewal_on"],
    titleField: "kind",
    order: { column: "renewal_on", ascending: true },
    due: [{ field: "renewal_on", label: "Insurance renewal" }],
  },
  {
    key: "vehicles",
    module: "compliance",
    table: "hub_vehicles",
    title: "Vehicles",
    singular: "vehicle",
    description: "Company vehicles and their MOT, tax, insurance and service dates.",
    fields: [text("registration", "Registration", { required: true }), text("make_model", "Make and model"), person("member_id", "Main driver"),
      date("mot_due_on", "MOT due"), date("tax_due_on", "Tax due"), date("insurance_due_on", "Insurance due"),
      date("service_due_on", "Service due"), area("notes", "Notes")],
    list: ["registration", "member_id", "mot_due_on", "tax_due_on", "insurance_due_on"],
    titleField: "registration",
    order: { column: "registration", ascending: true },
    due: [{ field: "mot_due_on", label: "MOT due" }, { field: "tax_due_on", label: "Vehicle tax due" },
      { field: "insurance_due_on", label: "Vehicle insurance due" }, { field: "service_due_on", label: "Service due" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "driver-checks",
    module: "compliance",
    table: "hub_driver_checks",
    title: "Driver checks",
    singular: "driver check",
    description: "Driving licence checks for anyone who drives for work.",
    fields: [person("member_id", "Driver", { required: true }), text("licence_number", "Licence number"),
      date("checked_on", "Checked on", { required: true }), num("points", "Points", { min: 0, max: 99 }), text("categories", "Categories"),
      yes("business_insurance_on_own_car", "Business use insurance on own car"), date("next_check_on", "Next check"), area("notes", "Notes")],
    list: ["member_id", "checked_on", "points", "next_check_on"],
    titleField: "checked_on",
    order: { column: "next_check_on", ascending: true },
    due: [{ field: "next_check_on", label: "Driver check due" }],
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "registrations",
    module: "compliance",
    table: "hub_registrations",
    title: "Registrations",
    singular: "registration",
    description: "Registrations with regulators and other bodies (ICO, CQC, waste carrier…).",
    fields: [text("body", "Body", { required: true }), text("reference", "Reference"), date("registered_on", "Registered"),
      date("renewal_on", "Renewal"), money("fee", "Fee"), area("notes", "Notes")],
    list: ["body", "reference", "renewal_on"],
    titleField: "body",
    order: { column: "renewal_on", ascending: true },
    due: [{ field: "renewal_on", label: "Registration renewal" }],
  },
];

const gdpr: RegisterDef[] = [
  {
    key: "data-map",
    module: "gdpr",
    table: "hub_ropa",
    title: "Data map",
    singular: "processing activity",
    description: "Your record of processing: what personal data you hold, why, and your lawful basis. Includes special category data.",
    fields: [text("data_category", "Data", { required: true, help: "e.g. Staff contact details, client health information" }),
      area("purpose", "Why you hold it", { required: true }), text("data_subjects", "Whose data"),
      pick("lawful_basis", "Lawful basis", opts({ contract: "Contract", legal_obligation: "Legal obligation", legitimate_interests: "Legitimate interests", consent: "Consent", vital_interests: "Vital interests", public_task: "Public task" })),
      yes("special_category", "Special category data"), text("special_condition", "Article 9 condition"),
      text("source", "Where it comes from"), text("retention", "How long you keep it"), text("storage_location", "Where it's stored"),
      text("shared_with", "Shared with"), area("security_measures", "Security measures"), date("review_on", "Review on")],
    list: ["data_category", "lawful_basis", "special_category", "review_on"],
    titleField: "data_category",
    order: { column: "data_category", ascending: true },
    due: [{ field: "review_on", label: "Data map review" }],
  },
  {
    key: "processors",
    module: "gdpr",
    table: "hub_processors",
    title: "Processor register",
    singular: "processor",
    description: "Suppliers who handle personal data for you, and your data processing agreements with them.",
    fields: [text("name", "Processor", { required: true }), text("service", "Service"), text("data_shared", "Data shared"),
      pick("location", "Where the data is", opts({ uk: "UK", eea: "EEA", adequate_country: "Adequate country", other: "Elsewhere" })),
      text("transfer_mechanism", "Transfer mechanism"), yes("dpa_signed", "Agreement signed"), date("dpa_signed_on", "Signed on"),
      date("review_on", "Review on")],
    list: ["name", "service", "dpa_signed", "review_on"],
    titleField: "name",
    order: { column: "name", ascending: true },
    due: [{ field: "review_on", label: "Processor review" }],
  },
  {
    key: "subject-access-requests",
    module: "gdpr",
    table: "hub_sars",
    title: "Subject access requests",
    singular: "subject access request",
    description: "Requests from people for a copy of their data. One calendar month to respond, or three if extended.",
    fields: [text("requester_name", "Requested by", { required: true }), email("requester_email", "Email"),
      date("received_on", "Received", { required: true }), yes("identity_verified", "Identity verified"),
      yes("extended", "Extended (complex request)"), date("due_on", "Respond by", { readonly: true }),
      pick("status", "Status", opts({ received: "Received", in_progress: "In progress", completed: "Completed", refused: "Refused" })),
      date("completed_on", "Completed on"), area("notes", "Notes")],
    list: ["requester_name", "received_on", "due_on", "status"],
    titleField: "requester_name",
    order: { column: "received_on", ascending: false },
    due: [{ field: "due_on", label: "Subject access request due" }],
    closedWhen: { field: "status", values: ["completed", "refused"] },
  },
  {
    key: "breaches",
    module: "gdpr",
    table: "hub_breaches",
    title: "Data breaches",
    singular: "breach",
    description: "Personal data breaches. A reportable breach must go to the ICO within 72 hours of discovery.",
    fields: [when("discovered_at", "Discovered", { required: true }), area("description", "What happened", { required: true }),
      text("data_affected", "Data affected"), num("individuals_affected", "People affected", { min: 0 }),
      pick("risk_level", "Risk to people", opts({ low: "Low", medium: "Medium", high: "High" })),
      yes("ico_reportable", "Reportable to the ICO"), when("reported_to_ico_at", "Reported to ICO"), text("ico_reference", "ICO reference"),
      yes("individuals_notified", "People told"), area("actions", "Actions"),
      pick("status", "Status", opts({ open: "Open", contained: "Contained", closed: "Closed" }))],
    list: ["discovered_at", "risk_level", "ico_reportable", "status"],
    titleField: "description",
    order: { column: "discovered_at", ascending: false },
    closedWhen: { field: "status", values: ["closed"] },
  },
  {
    key: "dpias",
    module: "gdpr",
    table: "hub_dpias",
    title: "DPIAs",
    singular: "data protection impact assessment",
    description: "Data protection impact assessments for new or risky uses of personal data.",
    fields: [text("project", "Project", { required: true }), area("description", "Description"), area("necessity", "Why it's necessary"),
      area("risks", "Risks"), area("mitigations", "Mitigations"),
      pick("residual_risk", "Remaining risk", opts({ low: "Low", medium: "Medium", high: "High" })),
      pick("outcome", "Outcome", opts({ in_progress: "In progress", approved: "Approved", approved_with_changes: "Approved with changes", rejected: "Rejected" })),
      text("approved_by", "Approved by"), date("completed_on", "Completed"), date("review_on", "Review on")],
    list: ["project", "outcome", "residual_risk", "review_on"],
    titleField: "project",
    order: { column: "created_at", ascending: false },
    due: [{ field: "review_on", label: "DPIA review" }],
  },
  {
    key: "privacy-notices",
    module: "gdpr",
    table: "hub_privacy_notices",
    title: "Privacy notices",
    singular: "privacy notice",
    description: "Privacy notices for customers, staff and job applicants. Published ones get a public link.",
    fields: [pick("audience", "For", opts({ customers: "Customers", staff: "Staff", job_applicants: "Job applicants", website: "Website visitors" })),
      text("title", "Title", { required: true }), area("body", "Wording", { required: true }), yes("published", "Published"),
      date("review_on", "Review on")],
    list: ["title", "audience", "published", "review_on"],
    titleField: "title",
    order: { column: "title", ascending: true },
    due: [{ field: "review_on", label: "Privacy notice review" }],
  },
];

const clients: RegisterDef[] = [
  {
    key: "clients",
    module: "clients",
    table: "hub_clients",
    title: "Clients",
    singular: "client",
    description: "Your clients and leads.",
    fields: [text("name", "Name", { required: true }), text("contact_name", "Contact"), email("email", "Email"), tel("phone", "Phone"),
      area("address", "Address"), pick("status", "Status", opts({ lead: "Lead", active: "Active", former: "Former" })),
      text("source", "How they found you"), area("notes", "Notes")],
    list: ["name", "contact_name", "status"],
    titleField: "name",
    order: { column: "name", ascending: true },
  },
  {
    key: "assessments",
    module: "clients",
    table: "hub_assessments",
    title: "Assessments",
    singular: "assessment",
    description: "Scheduled assessments and site visits. Staff see the ones they're booked on.",
    fields: [ref("client_id", "Client", "clients", { required: true }), when("scheduled_at", "When", { required: true }),
      person("member_id", "Assessor"), text("kind", "Type"),
      pick("status", "Status", opts({ scheduled: "Scheduled", done: "Done", cancelled: "Cancelled" })), area("outcome", "Outcome")],
    list: ["client_id", "scheduled_at", "member_id", "status"],
    titleField: "kind",
    order: { column: "scheduled_at", ascending: true },
    due: [{ field: "scheduled_at", label: "Assessment" }],
    closedWhen: { field: "status", values: ["done", "cancelled"] },
    memberField: "member_id",
    staff: { read: true },
  },
  {
    key: "disputes",
    module: "clients",
    table: "hub_disputes",
    title: "Disputes",
    singular: "dispute",
    description: "Complaints and disputes with clients, and how they were resolved.",
    fields: [ref("client_id", "Client", "clients", { required: true }), date("raised_on", "Raised"), area("summary", "Summary", { required: true }),
      pick("status", "Status", opts({ open: "Open", resolved: "Resolved" })), area("resolution", "Resolution"), date("resolved_on", "Resolved on")],
    list: ["client_id", "raised_on", "status"],
    titleField: "summary",
    order: { column: "raised_on", ascending: false },
    closedWhen: { field: "status", values: ["resolved"] },
  },
  {
    key: "contacts",
    module: "clients",
    table: "hub_contacts",
    title: "Networking",
    singular: "contact",
    description: "People you've met, and when to follow up.",
    fields: [text("name", "Name", { required: true }), text("organisation", "Organisation"), email("email", "Email"), tel("phone", "Phone"),
      text("met_at", "Where you met"), date("met_on", "Met on"), date("follow_up_on", "Follow up on"), area("notes", "Notes")],
    list: ["name", "organisation", "follow_up_on"],
    titleField: "name",
    order: { column: "follow_up_on", ascending: true },
    due: [{ field: "follow_up_on", label: "Follow up" }],
  },
];

const website: RegisterDef[] = [
  {
    key: "services",
    module: "website",
    table: "hub_services",
    title: "Services",
    singular: "service",
    description: "What you offer, shown on your public page.",
    fields: [text("name", "Service", { required: true }), area("description", "Description"), text("price", "Price", { help: "e.g. From £45" }),
      text("duration", "Duration"), yes("active", "Show on website", { defaultValue: "true" }), num("position", "Order", { min: 0 })],
    list: ["name", "price", "active"],
    titleField: "name",
    order: { column: "position", ascending: true },
  },
  {
    key: "booking-requests",
    module: "website",
    table: "hub_booking_requests",
    title: "Booking requests",
    singular: "booking request",
    description: "Requests sent through your public page.",
    fields: [text("customer_name", "Name", { required: true }), email("email", "Email"), tel("phone", "Phone"),
      ref("service_id", "Service", "services"), date("preferred_date", "Preferred date"), area("message", "Message"),
      pick("status", "Status", opts({ new: "New", contacted: "Contacted", booked: "Booked", declined: "Declined" }))],
    list: ["customer_name", "service_id", "preferred_date", "status"],
    titleField: "customer_name",
    order: { column: "created_at", ascending: false },
    closedWhen: { field: "status", values: ["booked", "declined"] },
  },
  {
    key: "customer-reviews",
    module: "website",
    table: "hub_reviews_public",
    title: "Reviews",
    singular: "review request",
    description: "Ask customers for a review by email. Approved reviews appear on your public page.",
    fields: [text("reviewer_name", "Customer name", { required: true }), email("email", "Email"), ref("client_id", "Client", "clients"),
      num("rating", "Rating", { readonly: true }), area("comment", "Comment", { readonly: true }),
      when("submitted_at", "Submitted", { readonly: true }), yes("approved", "Show on website")],
    list: ["reviewer_name", "rating", "submitted_at", "approved"],
    titleField: "reviewer_name",
    order: { column: "requested_at", ascending: false },
  },
];

const payroll: RegisterDef[] = [
  {
    key: "pay-details",
    module: "payroll",
    table: "hub_pay_details",
    title: "Pay details",
    singular: "pay details",
    description: "Pay rate, tax code, NI number and pension status. Owner only. Bank details stay in your payroll software.",
    fields: [person("member_id", "Person", { required: true }), text("payroll_id", "Payroll ID"),
      pick("pay_type", "Paid", opts({ hourly: "Hourly", salary: "Salary" })), money("rate", "Rate", { help: "Hourly rate, or annual salary" }),
      text("ni_number", "NI number"), text("tax_code", "Tax code"),
      pick("pension_status", "Pension", opts({ eligible: "Eligible, not enrolled", enrolled: "Enrolled", opted_out: "Opted out", postponed: "Postponed", not_eligible: "Not eligible" })),
      date("pension_enrolled_on", "Enrolled on"), date("pension_opt_out_on", "Opted out on"), date("re_enrolment_on", "Re-enrolment date"),
      area("notes", "Notes")],
    list: ["member_id", "pay_type", "rate", "pension_status"],
    titleField: "member_id",
    order: { column: "updated_at", ascending: false },
    due: [{ field: "re_enrolment_on", label: "Pension re-enrolment" }],
    minRole: "owner",
    memberField: "member_id",
    idColumn: "member_id",
    staff: { read: true },
  },
  {
    key: "timesheets",
    module: "payroll",
    table: "hub_timesheets",
    title: "Timesheets",
    singular: "timesheet entry",
    description: "Hours worked. Staff submit their own; approved hours go into the payroll export.",
    fields: [person("member_id", "Person", { required: true }), date("work_on", "Date", { required: true }),
      num("hours", "Hours", { required: true, min: 0.25, max: 24 }), area("notes", "Notes"),
      pick("status", "Status", opts({ submitted: "Submitted", approved: "Approved", rejected: "Rejected" }))],
    list: ["member_id", "work_on", "hours", "status"],
    titleField: "work_on",
    order: { column: "work_on", ascending: false },
    memberField: "member_id",
    staff: { read: true, create: { label: "Submit hours", fields: ["work_on", "hours", "notes"] } },
  },
  {
    key: "payroll-queries",
    module: "payroll",
    table: "hub_payroll_queries",
    title: "Payroll queries",
    singular: "payroll query",
    description: "Missing payslips, wrong tax or NI, holiday or sick pay not recorded.",
    fields: [person("member_id", "Person", { required: true }), date("raised_on", "Raised"),
      pick("kind", "Problem", opts({ other: "Other", missing_payslip: "Missing or wrong payslip", wrong_pay: "Wrong pay", wrong_tax: "Wrong tax", ni_error: "National Insurance error", holiday_not_recorded: "Holiday not recorded", sick_pay: "Sick pay", pension: "Pension" })),
      area("description", "Details", { required: true }),
      pick("status", "Status", opts({ open: "Open", with_provider: "With payroll provider", resolved: "Resolved" })),
      area("resolution", "Resolution"), date("resolved_on", "Resolved on")],
    list: ["member_id", "kind", "raised_on", "status"],
    titleField: "kind",
    order: { column: "raised_on", ascending: false },
    closedWhen: { field: "status", values: ["resolved"] },
    memberField: "member_id",
    staff: { read: true, create: { label: "Raise a pay problem", fields: ["kind", "description"] } },
  },
  {
    key: "payroll-runs",
    module: "payroll",
    table: "hub_payroll_runs",
    title: "Pay runs",
    singular: "pay run",
    description: "A checklist per pay period: exported, submitted to HMRC by your provider, payslips issued.",
    fields: [date("period_start", "Period from", { required: true }), date("period_end", "Period to", { required: true }),
      date("pay_on", "Pay day"), date("exported_on", "Exported to provider"), yes("fps_submitted", "FPS submitted to HMRC"),
      yes("payslips_issued", "Payslips issued"), yes("pension_submitted", "Pension contributions submitted"),
      pick("status", "Status", opts({ open: "Open", complete: "Complete" })), area("notes", "Notes")],
    list: ["period_start", "period_end", "pay_on", "status"],
    titleField: "period_end",
    order: { column: "period_start", ascending: false },
    due: [{ field: "pay_on", label: "Pay day" }],
    closedWhen: { field: "status", values: ["complete"] },
  },
];

const suppliers: RegisterDef[] = [
  {
    key: "suppliers",
    module: "suppliers",
    table: "hub_suppliers",
    title: "Suppliers",
    singular: "supplier",
    description: "Approved wholesalers and suppliers.",
    fields: [text("name", "Name", { required: true }), text("contact_name", "Contact"), email("email", "Email"), tel("phone", "Phone"),
      text("account_number", "Account number"), text("payment_terms", "Payment terms"), yes("approved", "Approved", { defaultValue: "true" }), area("notes", "Notes")],
    list: ["name", "contact_name", "approved"],
    titleField: "name",
    order: { column: "name", ascending: true },
  },
  {
    key: "products",
    module: "suppliers",
    table: "hub_products",
    title: "Products",
    singular: "product",
    description: "What you buy, stock levels and reorder points.",
    fields: [text("name", "Product", { required: true }), ref("supplier_id", "Supplier", "suppliers"),
      ref("coshh_id", "COSHH assessment", "coshh", { help: "Needs the Compliance module on to pick one." }),
      text("sku", "Code"), text("unit", "Unit"), money("unit_price", "Unit price"),
      num("stock_level", "In stock", { min: 0 }), num("reorder_level", "Reorder at", { min: 0 })],
    list: ["name", "supplier_id", "stock_level", "reorder_level"],
    titleField: "name",
    order: { column: "name", ascending: true },
  },
  {
    key: "orders",
    module: "suppliers",
    table: "hub_orders",
    title: "Orders",
    singular: "order",
    description: "Orders placed with suppliers.",
    fields: [ref("supplier_id", "Supplier", "suppliers", { required: true }), date("ordered_on", "Ordered on"),
      area("items", "Items", { required: true }), money("total", "Total"),
      pick("status", "Status", opts({ draft: "Draft", ordered: "Ordered", received: "Received", cancelled: "Cancelled" })),
      date("expected_on", "Expected"), date("received_on", "Received on"), area("notes", "Notes")],
    list: ["supplier_id", "ordered_on", "status", "total"],
    titleField: "ordered_on",
    order: { column: "ordered_on", ascending: false },
    due: [{ field: "expected_on", label: "Order expected" }],
    closedWhen: { field: "status", values: ["received", "cancelled"] },
  },
];

export const REGISTERS: RegisterDef[] = [...staffHub, ...compliance, ...gdpr, ...clients, ...website, ...payroll, ...suppliers];

export function getRegister(key: string): RegisterDef | undefined {
  return REGISTERS.find((r) => r.key === key);
}

export function registersForModule(module: string): RegisterDef[] {
  return REGISTERS.filter((r) => r.module === module);
}
